<?php
/**
 * @author      Oleh Kravets <oleh.kravets@snk.de>
 * @copyright   Copyright (c) 2021 schoene neue kinder GmbH  (https://www.snk.de)
 * @license     MIT
 */

/** @var \Snk\Captcha\Block\Captcha\MathCaptcha $block */

/** @var \Snk\Captcha\Model\MathCaptcha $captcha */
$captcha = $block->getCaptchaModel();
?>

<div class="field captcha required" role="<?= $block->escapeHtmlAttr($block->getFormId()) ?>">
    <label for="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>" class="label">
        <span><?= $block->escapeHtml($block->getLabelText()) ?></span>
    </label>
    <div class="control captcha">
        <input name="<?= $block->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE) ?>[<?= $block->escapeHtmlAttr($block->getFormId()) ?>]"
               type="text" class="input-text required-entry"
               data-validate="{required:true}"
               id="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
               autocomplete="off"/>
        <div class="nested">
            <div class="field captcha no-label"
                 data-captcha="<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
                 id="captcha-container-<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
                 data-mage-init='{"captcha":{"url": "<?= $block->escapeUrl($block->getRefreshUrl()) ?>",
                                            "imageLoader": "<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>",
                                             "type": "<?= $block->escapeHtmlAttr($block->getFormId()) ?>"}}'>
                <div class="control captcha-image">
                    <img alt="<?= $block->escapeHtmlAttr($block->getLabelText()) ?>"
                         class="captcha-img"
                         height="<?= /* @noEscape */ (float) $block->getImgHeight() ?>"
                         src="<?= $block->escapeUrl($captcha->getImgSrc()) ?>"/>
                    <button type="button" class="action reload captcha-reload" title="<?= $block->escapeHtmlAttr(__('Reload captcha')) ?>">
                        <span><?= $block->escapeHtml(__('Reload captcha')) ?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
