<?php
	$collection=$block->getSliderCollection();
	$url=$block->getImageurl();
	$currentFullAction = $block->getRequest()->getFullActionName();
	// echo "<pre>";
	echo $currentFullAction;
	// die;
	$collectionDAta=$collection->getData();

	// print_r($collectionDAta[0]['position']);
	// die;

	// if($collectionDAta[0]['position']== 1 && $currentFullAction='')
	// {
	// 	print_r('hello');
	// }
	// else
	// {
	// 	print_r('Not Selected Page');
	// }
	// if()
	// die;
	// echo $currentFullAction;
	// echo "<pre>";
	// print_r($block->toOptionArray());
	// die();
	// print_r($url);
	// die();
	// $count=0;
		// echo "<pre>";
	
	// echo "hello";
// die();
?>