<?php
namespace Plugindemo\Example\Plugin;
class NewUrl
{           
    protected $urlRewriteFactory;

    public function __construct(
        \Magento\UrlRewrite\Model\UrlRewriteFactory $urlRewriteFactory
    )
    {
        $this->_urlRewriteFactory = $urlRewriteFactory;     
    }

	public function afterSave(\Magento\Catalog\Model\Product $subject, $result)
    {
        $twinurl = $subject->getTwinUrl();
        $id = $subject->getEntityId();
        $data = [
            'entity_type' => 'product',
            'entity_id'   => $subject->getEntityId(),
            'request_path'=> $twinurl,
            'target_path' => 'catalog/product/view/id/'.$id,
            'redirect_type'=> 0,
            'store_id'=> 1,
            'description' => null,
            'is_autogenerated' => 0,
            'metadata' => null
        ];
        $model = $this->_urlRewriteFactory->create();
        $modeldata = $model->getCollection()->addFieldToFilter('target_path',['eq'=>'catalog/product/view/id/'.$id])->addFieldToFilter('is_autogenerated',0)->getLastItem();
        if(!$twinurl)
        {
            if($modeldata->getId()){
                $modeldata -> delete();
            }
            
        }
        else
        {
            if(!$modeldata->getId())
            {
                $model->setData($data);
                $model->save();
            }
            else
            {
               if($modeldata->getRequestPath() != $twinurl)
                {  
                    $modeldata->delete();                            
                    $model->setData($data);
                    $model->save();
                }
                   
            }
        }

    }
}