<?php
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="block block-searchs">
    <div class="block block-titles"><strong><?= $block->escapeHtml(__('Search')) ?></strong></div>
    <div class="block block-contents">
        <form class="form minisearchs" id="search_mini_forms"
              action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <div class="field searchs">
                <label class="label" for="searchs" data-role="minisearchs-label">
                </label>
                <div class="controls">
                    <input id="searchs"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_forms",
                                "url":"<?= $block->escapeUrl($helper->getSuggestUrl())?>",
                                "destinationSelector":"#search_autocompletes",
                                "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                           }'
                           type="text"
                           name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>"
                           class="input-text"
                           maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <div id="search_autocompletes" class="search-autocompletes"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                    title="<?= $block->escapeHtmlAttr(__('Search')) ?>"
                    class="action search"
                    aria-label="Search"
                >
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
