<?php $formId = 'product_addtocart_form'; ?>

<div class="buynow-button">
    <button type="submit"
            title="Buy Now"
            id="buy-now"
            class="buy-now-btn"
            data-mage-init='
            {
                "Ict_Buynow/js/buy-now": {
                    "form": "#<?= /* @noEscape */ $formId; ?>"
                }
            }
            '>
        <span>Buy Now</span>
    </button>
</div>