<?php
/**
 * Copyright © Icreative Technologies. All rights reserved.
 *
 * @author : Icreative Technologies
 * @package : Ict_Quickorder
 * @copyright : Copyright © Icreative Technologies (https://www.icreativetechnologies.com/)
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

$product = $block->getProductOptions();

$image = 'category_page_grid';
$_imagehelper = $this->helper(\Magento\Catalog\Helper\Image::class);
?>
<ul class="suggetion">
    <li class="lbl">
        <div class="image-label"><?= /* @noEscape */ __('Image') ?></div>
        <div class="name-label"><?= /* @noEscape */ __('Product Title') ?></div>
        <div class="sku-label"><?= /* @noEscape */ __('SKU') ?></div>
        <div class="price-label"><?= /* @noEscape */ __('Unit Price') ?></div>
    </li>
    <?php
    foreach ($product as $data) {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $_product = $objectManager->create(\Magento\Catalog\Model\ProductFactory::class)->create()->load($data['entity_id']);
        if ($_product->getTypeId() == 'configurable') {
            $_children = $_product->getTypeInstance()->getUsedProducts($_product);
            foreach ($_children as $child) {
                $arr[] = $child->getID();
            }
            $productSimple = $objectManager->create(\Magento\Catalog\Model\ProductFactory::class)->create()->load($arr[0]);
        } ?>
        <li>
            <div  class="image img-slide">
                <a href="javascript:void(0)" data="<?= /* @noEscape */ $_product->getSku(); ?>">
                    <img src="<?= /* @noEscape */
                        $_imagehelper->init($_product, $image)
                            ->constrainOnly(false)
                            ->keepAspectRatio(true)
                            ->keepFrame(false)
                            ->resize(150)
                            ->getUrl(); ?>" />
                </a>
            </div>
            <a href="javascript:void(0)" class="products-link" data="<?= /* @noEscape */ $_product->getSku(); ?>">
                <div class="name"><?= /* @noEscape */ $_product->getName(); ?></div>
            </a>
            <a href="javascript:void(0)" class="products-sku" data="<?= /* @noEscape */ $_product->getSku(); ?>">
                <div class="sku"><?= /* @noEscape */ $_product->getSku(); ?></div>
            </a>
            <div class="price">
            <?php if ($_product->getTypeId() == 'configurable') { ?>
                <span>Starting At</span>
                <?php $startingAtTextPrice = $this->helper(\Magento\Framework\Pricing\Helper\Data::class)
                        ->currency($productSimple->getPrice(), true, false);
                echo $block->escapeHtml($startingAtTextPrice);
            } else {
                $price = $this->helper(\Magento\Framework\Pricing\Helper\Data::class)->currency($_product
                        ->getPrice(), true, false);
                echo $block->escapeHtml($price);
            } ?>
            </div>
        </li>
    <?php } ?>
</ul>
